version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "s3://rl-fullstackdev-portfolio"
 post_build:
   commands:
     - aws cloudfront create-invalidation --distribution-id E1UT4ZKW39WTD8 --paths '/*'